"""empty message

Revision ID: 1dec65ac6cc6
Revises: 
Create Date: 2023-06-11 22:21:12.018894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dec65ac6cc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TickerData',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('quote_asset_volume', sa.Float(), nullable=False),
    sa.Column('number_of_trades', sa.Integer(), nullable=False),
    sa.Column('taker_buy_base_asset_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_quote_asset_volume', sa.Float(), nullable=False),
    sa.Column('ignore', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TickerData')
    # ### end Alembic commands ###
